#!/usr/bin/env bash
#
# install_zsh.sh
#
# Installs zsh, Oh My Zsh, Powerlevel10k, MesloLGS Nerd Font (+ Symbols Only),
# and the plugins zsh-autosuggestions, zsh-syntax-highlighting, zsh-completions.
#
# Targets:
#   - macOS                       (Homebrew)
#   - Debian / Ubuntu / Pi OS     (apt-get)
#   - Fedora / RHEL / Rocky / Alma (dnf)
#   - Arch / Manjaro              (pacman)
#   - Alpine                       (apk)
#   - openSUSE                    (zypper)
#
# Architecture-agnostic: x86_64, arm64/aarch64, armv7l (Pi, Gateworks, etc).
#
# Usage:  ./install_zsh.sh
# Do not run as root.
#
# The script is idempotent: rerunning it should not duplicate config or fail.
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

set -eo pipefail

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                       GLOBALS
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
OS="$(uname -s)"
ARCH="$(uname -m)"
PKG_MGR=""
SUDO=""
ZSHRC="$HOME/.zshrc"
ZSH_CUSTOM_DIR="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
NERD_FONTS_VERSION="v3.3.0"
PLUGINS=(zsh-autosuggestions zsh-syntax-highlighting zsh-completions)

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                   PRETTY OUTPUT — (KEEP IN SYNC WITH LINUX/BASE_FUNCTIONS.SH)
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Verified identical to linux/base_functions.sh by tests/test-theme-sync.sh.
# Palette and rules:
#   ~/vaults/dojobrain/30-references/design-system/itdojo-terminal-design-system.md
# QOL_SEL and QOL_OKBG have no reader in every script that embeds this block;
# a token ink with no consumer is suppressed, not deleted — dropping a color
# from a palette copy makes it a worse copy.
# shellcheck disable=SC2034
qol_init_color() {
    if [[ -n "${NO_COLOR:-}" ]]; then
        QOL_COLOR=""
    elif [[ -n "${QOL_FORCE_COLOR:-}" || -t 1 ]]; then
        QOL_COLOR=1
    else
        QOL_COLOR=""
    fi

    case "${QOL_COLOR_DEPTH:-truecolor}" in
        256)  QOL_DEPTH=256 ;;
        8)    QOL_DEPTH=8 ;;
        none) QOL_DEPTH=none ;;
        *)    QOL_DEPTH=truecolor ;;
    esac
    [[ -z "$QOL_COLOR" ]] && QOL_DEPTH=none

# ‒‒ generated by dojobrain scripts/build-design-tokens.py --emit-bash
# ‒‒ do not hand-edit; edit tokens/colors.css and re-emit.
    case "$QOL_DEPTH" in
        truecolor)
            QOL_STEP=$'\033[38;2;188;176;232m'
            QOL_PASS=$'\033[38;2;78;206;106m'
            QOL_INFO=$'\033[38;2;122;160;216m'
            QOL_WARN=$'\033[38;2;224;180;90m'
            QOL_STOP=$'\033[38;2;224;107;130m'
            QOL_FG=$'\033[38;2;228;222;245m'
            QOL_META=$'\033[38;2;154;147;181m'
            QOL_RULE=$'\033[38;2;74;65;112m'
            QOL_SEL=$'\033[48;2;36;29;61m'
            QOL_OKBG=$'\033[48;2;21;50;31m'
            ;;
        256)
            QOL_STEP=$'\033[38;5;140m'
            QOL_PASS=$'\033[38;5;77m'
            QOL_INFO=$'\033[38;5;110m'
            QOL_WARN=$'\033[38;5;179m'
            QOL_STOP=$'\033[38;5;168m'
            QOL_FG=$'\033[38;5;189m'
            QOL_META=$'\033[38;5;103m'
            QOL_RULE=$'\033[38;5;60m'
            QOL_SEL=$'\033[48;5;235m'
            QOL_OKBG=$'\033[48;5;22m'
            ;;
        8)
            QOL_STEP=$'\033[94m'
            QOL_PASS=$'\033[92m'
            QOL_INFO=$'\033[94m'
            QOL_WARN=$'\033[93m'
            QOL_STOP=$'\033[91m'
            QOL_FG=$'\033[97m'
            QOL_META=$'\033[90m'
            QOL_RULE=$'\033[90m'
            QOL_SEL=$'\033[7m'
            QOL_OKBG=$'\033[7m'
            ;;
        *)
            QOL_STEP="" QOL_PASS="" QOL_INFO="" QOL_WARN="" QOL_STOP="" QOL_FG="" QOL_META="" QOL_RULE="" QOL_SEL="" QOL_OKBG=""
            ;;
    esac
# ‒‒ end generated block

    if [[ "$QOL_DEPTH" == "none" ]]; then
        QOL_BOLD="" QOL_DIM="" QOL_RESET=""
    else
        QOL_BOLD=$'\033[1m'; QOL_DIM=$'\033[2m'; QOL_RESET=$'\033[0m'
    fi
}
qol_init_color

# Terminal width, falling back to 80 with no TTY (cron, CI, pipes).
#
# Ask the terminal, not terminfo. `tput cols 2>/dev/null` inside a command
# substitution answers 80 however wide the window is: with stdout captured,
# ncurses reads the window size off stderr instead, and that redirect throws
# the only usable fd away. Every rule, bookend and selection bar in this file
# was pinned to 80 columns by it. stty asks /dev/tty directly, so no amount of
# nesting can hide the answer. COLUMNS still wins when set, as an override.
#
# **Both the redirect order and the `|| true` are load-bearing, and neither is
# style.** With no controlling terminal — cron, CI, an agent, `ssh host cmd` —
# opening /dev/tty fails. Bash applies redirections left to right and reports a
# failed one on its own stderr, so `</dev/tty 2>/dev/null` prints
# `/dev/tty: Device not configured` past a suppression that is not in effect
# yet; putting `2>/dev/null` first silences it. That is only the noise. The
# failure is that the pipeline still exits non-zero, and a script running under
# `set -E` inherits its ERR trap into this command substitution and dies here —
# at its opening banner, before doing anything. Measured 2026-08-20:
# student-setup's `bootstrap.sh` (`set -Eeo pipefail`) reported
# `Failed at line 239` and stopped; the scripts in this repo use `set -eo` and
# only printed the message, which is why it read as cosmetic for a week.
# `|| true` is what makes the fallback to 80 a fallback rather than a fatality.
# With a real terminal nothing changes: stty answers, the pipeline exits 0, and
# `|| true` never fires.
_term_cols() {
    local cols="${COLUMNS:-}"
    if [[ ! "$cols" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
        cols="$(stty size 2>/dev/null </dev/tty | cut -d' ' -f2 || true)"
    fi
    if [[ ! "$cols" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
        cols=80
    fi
    printf '%s' "$cols"
}

# Repeat a character n times. Emits nothing for n <= 0.
_repeat() {
    local ch="$1" n="$2" line
    [[ "$n" =~ ^-?[0-9]+$ ]] || return 0
    (( n <= 0 )) && return 0
    printf -v line '%*s' "$n" ''
    printf '%s' "${line// /$ch}"
}

# One milestone line. The prefix is exactly 9 columns: gutter, space,
# 4-char badge, 3 spaces. Message text therefore starts at column 10.
_log_line() {
    local ink="$1" badge="$2" text="$3"
    printf '%s%s▌ %-4s   %s%s\n' "$QOL_BOLD" "$ink" "$badge" "$text" "$QOL_RESET"
}

log_step() { _log_line "$QOL_STEP" STEP "$1"; }
log_ok()   { _log_line "$QOL_PASS" PASS "$1"; }
log_info() { _log_line "$QOL_INFO" INFO "$1"; }
log_warn() { _log_line "$QOL_WARN" WARN "$1"; }
log_err()  { _log_line "$QOL_STOP" STOP "$1" >&2; }
log_ask()  { _log_line "$QOL_STEP" ASK  "$1"; }
log_next() { _log_line "$QOL_INFO" NEXT "$1"; }

# Phase boundary: a gray rule carrying the phase name in violet. A rule now
# means "new phase", which is information; a rule per line meant nothing.
log_phase() {
    local title="$1" cols fill
    cols="$(_term_cols)"
    fill=$(( cols - ${#title} - 4 ))
    printf '\n%s──%s %s%s%s%s %s%s\n\n' \
        "$QOL_RULE" "$QOL_RESET" \
        "$QOL_BOLD$QOL_STEP" "$title" "$QOL_RESET" \
        "$QOL_RULE" "$(_repeat '─' "$fill")" "$QOL_RESET"
}

# Run bookends. Jade rules, so a run's edges are findable when scrolling
# back through screens of package-manager output; phase rules are gray.
banner() {
    local title="$1" sub="${2:-}" cols
    cols="$(_term_cols)"
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    printf '  %s%s⛩ %s ⛩%s' "$QOL_BOLD" "$QOL_PASS" "$title" "$QOL_RESET"
    [[ -n "$sub" ]] && printf '   %s%s%s' "$QOL_META" "$sub" "$QOL_RESET"
    printf '\n%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# NOTE: not named `complete` — that is a bash builtin.
log_complete() {
    local title="$1" cols
    cols="$(_term_cols)"
    printf '\n%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    printf '  %s%s%s ⛩ %s ⛩ %s\n' "$QOL_OKBG" "$QOL_BOLD" "$QOL_PASS" "$title" "$QOL_RESET"
    printf '%s%s%s\n\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# ‒‒ Back-compat ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Eight other scripts call these. Kept working, not kept identical: printline
# no longer appears in any log_* line, because the design uses phase rules.

# Print a separator line the width of the terminal.
# Usage: printline [solid|bullet|ibeam|star|plus|diamond|dentistry]
printline() {
    local sep
    case "${1:-solid}" in
        bullet)    sep="•" ;;
        ibeam)     sep="⌶" ;;
        star)      sep="★" ;;
        plus)      sep="✛" ;;
        diamond)   sep="◆" ;;
        dentistry) sep="⏥" ;;
        *)         sep="─" ;;
    esac
    printf '%s%s%s\n' "$QOL_RULE" "$(_repeat "$sep" "$(_term_cols)")" "$QOL_RESET"
}

# Print styled text with no separator. Also usable inline via command
# substitution: echo "I am a $(style_text "Raspberry Pi" bold wine)."
# Usage: style_text "text" [normal|bold|light] [brand or legacy color name]
# Brand names:  violet jade steel saffron wine prose meta rule
# Legacy names: blue   green  —     yellow  red   —     —    —
style_text() {
    local text="$1" weight="${2:-normal}" color="${3:-}"
    local wt="" ink=""
    case "$weight" in
        bold)  wt="$QOL_BOLD" ;;
        light) wt="$QOL_DIM" ;;
    esac
    case "$color" in
        violet)        ink="$QOL_STEP" ;;
        jade|green)    ink="$QOL_PASS" ;;
        steel|blue)    ink="$QOL_INFO" ;;
        saffron|yellow) ink="$QOL_WARN" ;;
        wine|red)      ink="$QOL_STOP" ;;
        prose)         ink="$QOL_FG" ;;
        meta)          ink="$QOL_META" ;;
        rule)          ink="$QOL_RULE" ;;
    esac
    if [[ -z "$QOL_COLOR" ]] || [[ -z "$ink" && -z "$wt" ]]; then
        printf '%s\n' "$text"
        return 0
    fi
    printf '%s%s%s%s\n' "$wt" "$ink" "$text" "$QOL_RESET"
}

# Separator + styled text. Retained for callers that predate log_phase;
# new code should use log_phase or a log_* helper instead.
format_font() {
    printline
    style_text "$1" "${2:-bold}" "${3:-saffron}"
}

# Banner for script titles. Prefer banner/log_complete in new code.
log_title() {
    local cols
    cols="$(_term_cols)"
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    style_text "$1" bold jade
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# ‒‒ Interactive ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Three question shapes, sharing gotime's chrome. Prompts go to stderr so
# ask_value and ask_choice can be captured with $(...). All three skip the
# prompt and return the default when ASSUME_YES is set or stdin is not a
# TTY — the priority order install_nano.sh already follows.

# Decode one keypress into _KEY (and _KEYCH for digits). Bash 3.2 safe:
# no read -N, no fractional -t. Arrows arrive as ESC then "[A"/"OA".
_read_key() {
    local k s
    _KEY=""; _KEYCH=""
    IFS= read -rsn1 k || { _KEY="QUIT"; return 0; }
    if [[ -z "$k" ]]; then _KEY="ENTER"; return 0; fi
    case "$k" in
        $'\r'|$'\n') _KEY="ENTER" ;;
        $'\x1b')
            s=""
            IFS= read -rsn2 -t 1 s
            case "$s" in
                '[A'|'OA') _KEY="UP" ;;
                '[B'|'OB') _KEY="DOWN" ;;
                '')        _KEY="QUIT" ;;
                *)         _KEY="OTHER" ;;
            esac ;;
        [0-9]) _KEY="DIGIT"; _KEYCH="$k" ;;
        k|K)   _KEY="UP" ;;
        j|J)   _KEY="DOWN" ;;
        q|Q)   _KEY="QUIT" ;;
        *)     _KEY="OTHER" ;;
    esac
    return 0
}

# ask_confirm "question" [Y|N]  ->  exit 0 for yes, 1 for no
ask_confirm() {
    local q="$1" def="${2:-N}" hint reply
    if [[ -n "${ASSUME_YES:-}" ]]; then return 0; fi
    if [[ ! -t 0 ]]; then [[ "$def" == "Y" ]]; return $?; fi
    if [[ "$def" == "Y" ]]; then hint="Y/n"; else hint="y/N"; fi
    _log_line "$QOL_STEP" ASK "$q" >&2
    printf '    %s❯%s %s[%s]%s ' "$QOL_PASS" "$QOL_RESET" "$QOL_META" "$hint" "$QOL_RESET" >&2
    read -r reply
    reply="${reply:-$def}"
    case "$reply" in [Yy]*) return 0 ;; *) return 1 ;; esac
}

# ask_value "question" "default" ["hint"]  ->  echoes the answer
ask_value() {
    local q="$1" def="$2" hint="${3:-}" reply
    if [[ -n "${ASSUME_YES:-}" || ! -t 0 ]]; then printf '%s' "$def"; return 0; fi
    _log_line "$QOL_STEP" ASK "$q" >&2
    [[ -n "$hint" ]] && printf '         %s%s%s\n' "$QOL_META" "$hint" "$QOL_RESET" >&2
    printf '    %s❯%s [%s%s%s] ' "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$def" "$QOL_RESET" >&2
    read -r reply
    printf '%s' "${reply:-$def}"
}

# Draw the choice list. Emits exactly (count + 3) lines so the caller knows
# how far to move the cursor back up when redrawing.
_ask_choice_draw() {
    local heading="$1" sel="$2"; shift 2
    local i=0 item label hint plain pad cols
    cols="$(_term_cols)"
    printf '\n %s%s%s%s\n' "$QOL_BOLD" "$QOL_STEP" "$heading" "$QOL_RESET"
    for item in "$@"; do
        label="${item%%|*}"
        hint="${item#*|}"; [[ "$hint" == "$item" ]] && hint=""
        # Pad every row out to the full width with real spaces. The selection
        # bar has to reach the right edge, and CLR_EOL cannot carry it there:
        # screen and tmux report no `bce`, so ESC[K erases to the default
        # background and cuts the bar off where the text ended. Padding the
        # unselected rows is what paints over the bar as it moves away.
        # Three leading columns in both branches: " ❯ " when selected, three
        # spaces when not. Measure the same shape the row actually prints.
        printf -v plain '   %2d   %-18s %s' "$(( i + 1 ))" "$label" "$hint"
        pad=$(( cols - ${#plain} ))
        (( pad < 0 )) && pad=0
        if (( i == sel )); then
            printf '%s%s%s ❯ %2d   %-18s %s%*s%s\n' \
                "$QOL_SEL" "$QOL_BOLD" "$QOL_PASS" "$(( i + 1 ))" "$label" "$hint" \
                "$pad" '' "$QOL_RESET"
        else
            printf '   %s%2d%s   %s%-18s%s %s%s%s%*s\n' \
                "$QOL_META" "$(( i + 1 ))" "$QOL_RESET" \
                "$QOL_FG" "$label" "$QOL_RESET" "$QOL_META" "$hint" "$QOL_RESET" \
                "$pad" ''
        fi
        i=$(( i + 1 ))
    done
    printf ' %s↑/↓%s or %sj/k%s move   %s1-9%s jump   %s⏎%s select\n' \
        "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$QOL_RESET" \
        "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$QOL_RESET"
}

# ask_choice "HEADING" default_index "label|hint" [...]  ->  echoes 1-based index
# Redraws in place rather than taking the alternate screen: an installer that
# blanks the scrollback has destroyed the record of what it just did.
ask_choice() {
    local heading="$1" def="$2"; shift 2
    local n=$#
    local sel=$(( def - 1 ))
    if [[ -n "${ASSUME_YES:-}" || ! -t 0 ]]; then printf '%s' "$def"; return 0; fi
    _ask_choice_draw "$heading" "$sel" "$@" >&2
    while true; do
        _read_key
        case "$_KEY" in
            ENTER) break ;;
            QUIT)  sel=$(( def - 1 )); break ;;
            UP)    sel=$(( (sel - 1 + n) % n )) ;;
            DOWN)  sel=$(( (sel + 1) % n )) ;;
            DIGIT) if (( 10#$_KEYCH >= 1 && 10#$_KEYCH <= n )); then sel=$(( 10#$_KEYCH - 1 )); fi ;;
        esac
        printf '\033[%dA' $(( n + 3 )) >&2
        _ask_choice_draw "$heading" "$sel" "$@" >&2
    done
    printf '%s' "$(( sel + 1 ))"
}
# ‒‒ end theme block

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                        SAFETY
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
handle_ctrl_c() {
    echo
    log_err "Interrupted. Exiting."
    exit 130
}
trap handle_ctrl_c INT

handle_err() {
    local exit_code=$?
    log_err "Error on line $1 (exit $exit_code). Aborting."
    exit "$exit_code"
}
trap 'handle_err $LINENO' ERR

check_for_root() {
    if [[ $EUID -eq 0 ]]; then
        log_err "Do not run as root. You'll be prompted for sudo if needed."
        exit 1
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                     PACKAGE MANAGER DETECTION
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
detect_package_manager() {
    if [[ "$OS" == "Darwin" ]]; then
        PKG_MGR="brew"
        return
    fi
    for cmd in apt-get dnf pacman apk zypper; do
        if command -v "$cmd" &>/dev/null; then
            PKG_MGR="$cmd"
            return
        fi
    done
    log_err "No supported package manager found (apt-get, dnf, pacman, apk, zypper, brew)."
    exit 1
}

setup_sudo() {
    if [[ "$OS" != "Darwin" ]] && command -v sudo &>/dev/null; then
        SUDO="sudo"
    fi
}

pkg_install() {
    local pkgs=("$@")
    case "$PKG_MGR" in
        brew)
            for p in "${pkgs[@]}"; do
                brew list --formula "$p" &>/dev/null || brew install "$p"
            done
            ;;
        apt-get)
            $SUDO apt-get update -qq
            $SUDO DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends "${pkgs[@]}"
            ;;
        dnf)
            $SUDO dnf install -y "${pkgs[@]}"
            ;;
        pacman)
            $SUDO pacman -Sy --noconfirm --needed "${pkgs[@]}"
            ;;
        apk)
            $SUDO apk add --no-cache "${pkgs[@]}"
            ;;
        zypper)
            $SUDO zypper install -y "${pkgs[@]}"
            ;;
    esac
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                HOMEBREW (MACOS ONLY) — MUST HAPPEN BEFORE ANYTHING CALLS BREW
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
ensure_homebrew() {
    [[ "$OS" == "Darwin" ]] || return 0
    if ! command -v brew &>/dev/null; then
        log_step "Installing Homebrew..."
        NONINTERACTIVE=1 /bin/bash -c \
            "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        if   [[ -x /opt/homebrew/bin/brew ]]; then eval "$(/opt/homebrew/bin/brew shellenv)"
        elif [[ -x /usr/local/bin/brew    ]]; then eval "$(/usr/local/bin/brew shellenv)"
        fi
    fi
    log_ok "Homebrew is installed."
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                           GENERIC TOOL INSTALLER (idempotent)
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
ensure_tool() {
    local tool="$1" pkg="${2:-$1}"
    if command -v "$tool" &>/dev/null; then
        log_ok "$tool is already installed."
        return
    fi
    log_step "Installing $tool..."
    pkg_install "$pkg"
    log_ok "$tool is installed."
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                     OH MY ZSH
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
ensure_oh_my_zsh() {
    if [[ -d "$HOME/.oh-my-zsh" ]]; then
        log_ok "Oh My Zsh is already installed."
        return
    fi
    log_step "Installing Oh My Zsh..."
    RUNZSH=no CHSH=no KEEP_ZSHRC=yes \
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" \
        "" --unattended
    log_ok "Oh My Zsh is installed."
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                 POWERLEVEL10K
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
install_powerlevel10k() {
    local p10k_dir="$ZSH_CUSTOM_DIR/themes/powerlevel10k"
    if [[ -d "$p10k_dir/.git" ]]; then
        log_info "Powerlevel10k already cloned; pulling latest..."
        git -C "$p10k_dir" pull --ff-only --quiet || log_warn "p10k pull failed; continuing."
    else
        log_step "Cloning Powerlevel10k..."
        git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$p10k_dir"
    fi
    log_ok "Powerlevel10k is installed."
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                       PLUGINS
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
install_zsh_plugins() {
    log_step "Installing Zsh plugins..."
    local plugin dest
    for plugin in "${PLUGINS[@]}"; do
        dest="$ZSH_CUSTOM_DIR/plugins/$plugin"
        if [[ -d "$dest/.git" ]]; then
            log_info "$plugin already cloned; pulling latest..."
            git -C "$dest" pull --ff-only --quiet || log_warn "$plugin pull failed."
        else
            git clone --depth=1 "https://github.com/zsh-users/$plugin.git" "$dest"
        fi
    done
    log_ok "Zsh plugins are installed."
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                    NERD FONTS
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
install_nerd_fonts() {
    log_step "Installing Nerd Fonts (MesloLGS NF + Symbols Only)..."
    if [[ "$OS" == "Darwin" ]]; then
        # Modern homebrew-cask carries fonts in the main cask repo.
        brew install --cask font-meslo-lg-nerd-font font-symbols-only-nerd-font \
            || log_warn "One or more font casks failed to install."
    else
        local fonts_dir="$HOME/.local/share/fonts"
        mkdir -p "$fonts_dir"
        local meslo_url="https://github.com/ryanoasis/nerd-fonts/releases/download/${NERD_FONTS_VERSION}/Meslo.zip"
        local symbols_url="https://github.com/ryanoasis/nerd-fonts/releases/download/${NERD_FONTS_VERSION}/NerdFontsSymbolsOnly.zip"
        local tmp; tmp="$(mktemp -d)"

        ensure_tool unzip
        ensure_tool fc-cache fontconfig

        log_info "Downloading Meslo Nerd Font (${NERD_FONTS_VERSION})..."
        curl -fSL "$meslo_url"   -o "$tmp/Meslo.zip"
        log_info "Downloading Nerd Fonts Symbols Only (${NERD_FONTS_VERSION})..."
        curl -fSL "$symbols_url" -o "$tmp/Symbols.zip"

        unzip -oq "$tmp/Meslo.zip"   -d "$fonts_dir/"
        unzip -oq "$tmp/Symbols.zip" -d "$fonts_dir/"
        rm -rf "$tmp"

        fc-cache -f "$fonts_dir" >/dev/null
    fi
    log_ok "Nerd Fonts are installed."
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                           .ZSHRC EDITING HELPERS (idempotent)
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
ensure_line_in_file() {
    local line="$1" file="$2"
    [[ -f "$file" ]] || touch "$file"
    grep -qxF "$line" "$file" || printf '%s\n' "$line" >> "$file"
}

# Overwrite dst with the contents of src, keeping dst's mode, owner and inode.
# `mv tmp dst` would be simpler but carries the temp file's permissions across —
# mktemp creates 0600, so that silently tightens a normal 0644 .zshrc.
replace_file_contents() {
    local src="$1" dst="$2"
    cat "$src" > "$dst"
    rm -f "$src"
}

# Replace `plugins=( ... )` block (single- or multi-line) with one canonical line.
replace_plugins_block() {
    local file="$1" new_line="$2" tmp
    tmp="$(mktemp)"
    awk -v new="$new_line" '
        BEGIN { skip = 0; replaced = 0 }
        /^plugins=\(/ {
            if (!replaced) { print new; replaced = 1 }
            if ($0 ~ /\)/) { next }
            skip = 1; next
        }
        skip {
            if ($0 ~ /\)/) { skip = 0 }
            next
        }
        { print }
        END {
            if (!replaced) { print new }
        }
    ' "$file" > "$tmp"
    replace_file_contents "$tmp" "$file"
}

cleanup_legacy_zshrc() {
    # Sweep up artifacts left by older versions of this script so reruns are clean:
    #   * stray `source .../powerlevel10k.zsh-theme` line that pointed at a
    #     non-existent brew path on macOS
    #   * duplicate `set -o AUTO_CD` lines appended on every previous run
    [[ -f "$ZSHRC" ]] || return 0
    local tmp; tmp="$(mktemp)"
    awk '
        # Drop any line that sources a powerlevel10k.zsh-theme outside our $ZSH_CUSTOM
        # tree. The new install loads p10k via the Oh My Zsh ZSH_THEME setting.
        /^[[:space:]]*source[[:space:]].*powerlevel10k\.zsh-theme/ { next }
        # Collapse repeated `set -o AUTO_CD` lines down to zero (we add `setopt AUTO_CD` later).
        /^[[:space:]]*set[[:space:]]+-o[[:space:]]+AUTO_CD[[:space:]]*$/ { next }
        { print }
    ' "$ZSHRC" > "$tmp"
    replace_file_contents "$tmp" "$ZSHRC"
}

update_zshrc() {
    log_step "Updating $ZSHRC..."
    [[ -f "$ZSHRC" ]] || touch "$ZSHRC"

    # One-time backup with timestamp (don't clobber existing backups).
    if ! ls "$ZSHRC".preinstall_zsh.* &>/dev/null; then
        cp "$ZSHRC" "$ZSHRC.preinstall_zsh.$(date +%Y%m%d-%H%M%S).bak"
    fi

    cleanup_legacy_zshrc

    # Theme
    if grep -q '^ZSH_THEME=' "$ZSHRC"; then
        # Portable in-place edit: sed to a temp file then mv (works on BSD + GNU sed).
        local tmp; tmp="$(mktemp)"
        sed 's|^ZSH_THEME=.*|ZSH_THEME="powerlevel10k/powerlevel10k"|' "$ZSHRC" > "$tmp"
        replace_file_contents "$tmp" "$ZSHRC"
    else
        ensure_line_in_file 'ZSH_THEME="powerlevel10k/powerlevel10k"' "$ZSHRC"
    fi

    # Plugins
    replace_plugins_block "$ZSHRC" \
        'plugins=(git zsh-autosuggestions zsh-syntax-highlighting zsh-completions)'

    # zsh-completions needs to be on fpath BEFORE compinit runs.
    # Oh My Zsh runs compinit in oh-my-zsh.sh, so we add this BEFORE the
    # `source $ZSH/oh-my-zsh.sh` line if possible, otherwise just append.
    local fpath_line='fpath+=("'"$ZSH_CUSTOM_DIR"'/plugins/zsh-completions/src")'
    if ! grep -qxF "$fpath_line" "$ZSHRC"; then
        if grep -q '^source \$ZSH/oh-my-zsh.sh' "$ZSHRC"; then
            local tmp; tmp="$(mktemp)"
            awk -v line="$fpath_line" '
                /^source \$ZSH\/oh-my-zsh\.sh/ && !done { print line; done = 1 }
                { print }
            ' "$ZSHRC" > "$tmp"
            replace_file_contents "$tmp" "$ZSHRC"
        else
            printf '%s\n' "$fpath_line" >> "$ZSHRC"
        fi
    fi

    # Quality-of-life options
    ensure_line_in_file 'setopt AUTO_CD' "$ZSHRC"

    log_ok "$ZSHRC updated."
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                 DEFAULT SHELL
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
change_default_shell() {
    local zsh_path
    zsh_path="$(command -v zsh)" || { log_warn "zsh not on PATH; skipping chsh."; return; }

    if [[ "${SHELL:-}" == "$zsh_path" ]]; then
        log_ok "Default shell is already zsh."
        return
    fi

    # Some distros refuse chsh to a shell that isn't in /etc/shells.
    if [[ -f /etc/shells ]] && ! grep -qxF "$zsh_path" /etc/shells; then
        log_info "Registering $zsh_path in /etc/shells..."
        echo "$zsh_path" | $SUDO tee -a /etc/shells >/dev/null || true
    fi

    log_step "Changing default shell to zsh ($zsh_path). You may be prompted for your password."
    if chsh -s "$zsh_path"; then
        log_ok "Default shell changed to zsh."
    else
        log_warn "chsh failed. You can change it manually with:  chsh -s $zsh_path"
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                                                                          MAIN
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
main() {
    banner "ZSH + POWERLEVEL10K" "shell · prompt · fonts · plugins"

    log_phase "PREFLIGHT"
    check_for_root
    detect_package_manager
    setup_sudo
    log_info "OS=$OS  ARCH=$ARCH  PKG_MGR=$PKG_MGR"

    log_phase "PACKAGES"
    ensure_homebrew         # macOS: bootstrap brew BEFORE anything that uses it

    # Core dependencies
    ensure_tool git
    ensure_tool curl
    ensure_tool wget
    ensure_tool zsh

    ensure_oh_my_zsh
    install_powerlevel10k
    install_zsh_plugins

    log_phase "FONTS"
    install_nerd_fonts

    log_phase "CONFIG"
    update_zshrc

    log_phase "DEFAULT SHELL"
    change_default_shell

    log_complete "ZSH + POWERLEVEL10K INSTALLED"
    log_next "Restart your terminal. The Powerlevel10k setup wizard runs on first launch."
    log_next "Reconfigure the prompt any time:  p10k configure"
    log_next "If glyphs render as boxes, set your terminal font to 'MesloLGS NF'."
    echo
}

main "$@"
