#!/usr/bin/env bash
#
# uninstall_omz_p10k.sh
#
# Removes Oh My Zsh and Powerlevel10k and strips their references out of
# ~/.zshrc. Your own .zshrc content is preserved: the file is edited line by
# line, not replaced, and a timestamped backup is taken first.
#
# Targets:
#   - macOS                       (also removes the brew powerlevel10k formula
#                                  and the font-meslo-for-powerlevel10k cask)
#   - Debian / Ubuntu             (and, incidentally, any other Linux — the
#                                  removal is almost entirely home-directory
#                                  paths)
#
# Usage:
#   ./uninstall_omz_p10k.sh                # confirm, then remove
#   ./uninstall_omz_p10k.sh --dry-run      # print the plan, change nothing
#   ./uninstall_omz_p10k.sh --yes          # no prompt (for automation)
#
#   source uninstall_omz_p10k.sh           # from another script
#   uninstall_omz_p10k                     # ...then call the function
#
# Return codes from uninstall_omz_p10k:
#   0   = removed, nothing to remove, or user kept the install ('n')
#   1   = failed (the .zshrc edit did not survive its syntax check and was
#         rolled back; nothing else was touched)
#   130 = user chose 'q' (the caller should abort)
#
# This script deliberately does NOT run ~/.oh-my-zsh/tools/uninstall.sh. That
# one restores ~/.zshrc.pre-oh-my-zsh, which on most machines is a handful of
# lines written the day Oh My Zsh was installed — everything added since would
# be lost. Do not run as root.
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒-

set -eo pipefail

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Globals
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
OS="$(uname -s)"
ZSHRC="${ZSHRC:-$HOME/.zshrc}"
OMZ_DIR="$HOME/.oh-my-zsh"
P10K_RC="$HOME/.p10k.zsh"
DRY_RUN=""
ASSUME_YES=""
FOUND_PATHS=()
FOUND_ZSHRC=""
FOUND_BREW=()

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
#                   PRETTY OUTPUT — (KEEP IN SYNC WITH LINUX/BASE_FUNCTIONS.SH)
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Verified identical to linux/base_functions.sh by tests/test-theme-sync.sh.
# Palette and rules:
#   ~/vaults/dojobrain/30-references/design-system/itdojo-terminal-design-system.md
# QOL_SEL and QOL_OKBG have no reader in every script that embeds this block;
# a token ink with no consumer is suppressed, not deleted — dropping a color
# from a palette copy makes it a worse copy.
# shellcheck disable=SC2034
qol_init_color() {
    if [[ -n "${NO_COLOR:-}" ]]; then
        QOL_COLOR=""
    elif [[ -n "${QOL_FORCE_COLOR:-}" || -t 1 ]]; then
        QOL_COLOR=1
    else
        QOL_COLOR=""
    fi

    case "${QOL_COLOR_DEPTH:-truecolor}" in
        256)  QOL_DEPTH=256 ;;
        8)    QOL_DEPTH=8 ;;
        none) QOL_DEPTH=none ;;
        *)    QOL_DEPTH=truecolor ;;
    esac
    [[ -z "$QOL_COLOR" ]] && QOL_DEPTH=none

# ‒‒ generated by dojobrain scripts/build-design-tokens.py --emit-bash
# ‒‒ do not hand-edit; edit tokens/colors.css and re-emit.
    case "$QOL_DEPTH" in
        truecolor)
            QOL_STEP=$'\033[38;2;188;176;232m'
            QOL_PASS=$'\033[38;2;78;206;106m'
            QOL_INFO=$'\033[38;2;122;160;216m'
            QOL_WARN=$'\033[38;2;224;180;90m'
            QOL_STOP=$'\033[38;2;224;107;130m'
            QOL_FG=$'\033[38;2;228;222;245m'
            QOL_META=$'\033[38;2;154;147;181m'
            QOL_RULE=$'\033[38;2;74;65;112m'
            QOL_SEL=$'\033[48;2;36;29;61m'
            QOL_OKBG=$'\033[48;2;21;50;31m'
            ;;
        256)
            QOL_STEP=$'\033[38;5;140m'
            QOL_PASS=$'\033[38;5;77m'
            QOL_INFO=$'\033[38;5;110m'
            QOL_WARN=$'\033[38;5;179m'
            QOL_STOP=$'\033[38;5;168m'
            QOL_FG=$'\033[38;5;189m'
            QOL_META=$'\033[38;5;103m'
            QOL_RULE=$'\033[38;5;60m'
            QOL_SEL=$'\033[48;5;235m'
            QOL_OKBG=$'\033[48;5;22m'
            ;;
        8)
            QOL_STEP=$'\033[94m'
            QOL_PASS=$'\033[92m'
            QOL_INFO=$'\033[94m'
            QOL_WARN=$'\033[93m'
            QOL_STOP=$'\033[91m'
            QOL_FG=$'\033[97m'
            QOL_META=$'\033[90m'
            QOL_RULE=$'\033[90m'
            QOL_SEL=$'\033[7m'
            QOL_OKBG=$'\033[7m'
            ;;
        *)
            QOL_STEP="" QOL_PASS="" QOL_INFO="" QOL_WARN="" QOL_STOP="" QOL_FG="" QOL_META="" QOL_RULE="" QOL_SEL="" QOL_OKBG=""
            ;;
    esac
# ‒‒ end generated block

    if [[ "$QOL_DEPTH" == "none" ]]; then
        QOL_BOLD="" QOL_DIM="" QOL_RESET=""
    else
        QOL_BOLD=$'\033[1m'; QOL_DIM=$'\033[2m'; QOL_RESET=$'\033[0m'
    fi
}
qol_init_color

# Terminal width, falling back to 80 with no TTY (cron, CI, pipes).
#
# Ask the terminal, not terminfo. `tput cols 2>/dev/null` inside a command
# substitution answers 80 however wide the window is: with stdout captured,
# ncurses reads the window size off stderr instead, and that redirect throws
# the only usable fd away. Every rule, bookend and selection bar in this file
# was pinned to 80 columns by it. stty asks /dev/tty directly, so no amount of
# nesting can hide the answer. COLUMNS still wins when set, as an override.
_term_cols() {
    local cols="${COLUMNS:-}"
    if [[ ! "$cols" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
        cols="$(stty size </dev/tty 2>/dev/null | cut -d' ' -f2)"
    fi
    if [[ ! "$cols" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
        cols=80
    fi
    printf '%s' "$cols"
}

# Repeat a character n times. Emits nothing for n <= 0.
_repeat() {
    local ch="$1" n="$2" line
    [[ "$n" =~ ^-?[0-9]+$ ]] || return 0
    (( n <= 0 )) && return 0
    printf -v line '%*s' "$n" ''
    printf '%s' "${line// /$ch}"
}

# One milestone line. The prefix is exactly 9 columns: gutter, space,
# 4-char badge, 3 spaces. Message text therefore starts at column 10.
_log_line() {
    local ink="$1" badge="$2" text="$3"
    printf '%s%s▌ %-4s   %s%s\n' "$QOL_BOLD" "$ink" "$badge" "$text" "$QOL_RESET"
}

log_step() { _log_line "$QOL_STEP" STEP "$1"; }
log_ok()   { _log_line "$QOL_PASS" PASS "$1"; }
log_info() { _log_line "$QOL_INFO" INFO "$1"; }
log_warn() { _log_line "$QOL_WARN" WARN "$1"; }
log_err()  { _log_line "$QOL_STOP" STOP "$1" >&2; }
log_ask()  { _log_line "$QOL_STEP" ASK  "$1"; }
log_next() { _log_line "$QOL_INFO" NEXT "$1"; }

# Phase boundary: a gray rule carrying the phase name in violet. A rule now
# means "new phase", which is information; a rule per line meant nothing.
log_phase() {
    local title="$1" cols fill
    cols="$(_term_cols)"
    fill=$(( cols - ${#title} - 4 ))
    printf '\n%s──%s %s%s%s%s %s%s\n\n' \
        "$QOL_RULE" "$QOL_RESET" \
        "$QOL_BOLD$QOL_STEP" "$title" "$QOL_RESET" \
        "$QOL_RULE" "$(_repeat '─' "$fill")" "$QOL_RESET"
}

# Run bookends. Jade rules, so a run's edges are findable when scrolling
# back through screens of package-manager output; phase rules are gray.
banner() {
    local title="$1" sub="${2:-}" cols
    cols="$(_term_cols)"
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    printf '  %s%s⛩ %s ⛩%s' "$QOL_BOLD" "$QOL_PASS" "$title" "$QOL_RESET"
    [[ -n "$sub" ]] && printf '   %s%s%s' "$QOL_META" "$sub" "$QOL_RESET"
    printf '\n%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# NOTE: not named `complete` — that is a bash builtin.
log_complete() {
    local title="$1" cols
    cols="$(_term_cols)"
    printf '\n%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    printf '  %s%s%s ⛩ %s ⛩ %s\n' "$QOL_OKBG" "$QOL_BOLD" "$QOL_PASS" "$title" "$QOL_RESET"
    printf '%s%s%s\n\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# ‒‒ Back-compat ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Eight other scripts call these. Kept working, not kept identical: printline
# no longer appears in any log_* line, because the design uses phase rules.

# Print a separator line the width of the terminal.
# Usage: printline [solid|bullet|ibeam|star|plus|diamond|dentistry]
printline() {
    local sep
    case "${1:-solid}" in
        bullet)    sep="•" ;;
        ibeam)     sep="⌶" ;;
        star)      sep="★" ;;
        plus)      sep="✛" ;;
        diamond)   sep="◆" ;;
        dentistry) sep="⏥" ;;
        *)         sep="─" ;;
    esac
    printf '%s%s%s\n' "$QOL_RULE" "$(_repeat "$sep" "$(_term_cols)")" "$QOL_RESET"
}

# Print styled text with no separator. Also usable inline via command
# substitution: echo "I am a $(style_text "Raspberry Pi" bold wine)."
# Usage: style_text "text" [normal|bold|light] [brand or legacy color name]
# Brand names:  violet jade steel saffron wine prose meta rule
# Legacy names: blue   green  —     yellow  red   —     —    —
style_text() {
    local text="$1" weight="${2:-normal}" color="${3:-}"
    local wt="" ink=""
    case "$weight" in
        bold)  wt="$QOL_BOLD" ;;
        light) wt="$QOL_DIM" ;;
    esac
    case "$color" in
        violet)        ink="$QOL_STEP" ;;
        jade|green)    ink="$QOL_PASS" ;;
        steel|blue)    ink="$QOL_INFO" ;;
        saffron|yellow) ink="$QOL_WARN" ;;
        wine|red)      ink="$QOL_STOP" ;;
        prose)         ink="$QOL_FG" ;;
        meta)          ink="$QOL_META" ;;
        rule)          ink="$QOL_RULE" ;;
    esac
    if [[ -z "$QOL_COLOR" ]] || [[ -z "$ink" && -z "$wt" ]]; then
        printf '%s\n' "$text"
        return 0
    fi
    printf '%s%s%s%s\n' "$wt" "$ink" "$text" "$QOL_RESET"
}

# Separator + styled text. Retained for callers that predate log_phase;
# new code should use log_phase or a log_* helper instead.
format_font() {
    printline
    style_text "$1" "${2:-bold}" "${3:-saffron}"
}

# Banner for script titles. Prefer banner/log_complete in new code.
log_title() {
    local cols
    cols="$(_term_cols)"
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    style_text "$1" bold jade
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# ‒‒ Interactive ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Three question shapes, sharing gotime's chrome. Prompts go to stderr so
# ask_value and ask_choice can be captured with $(...). All three skip the
# prompt and return the default when ASSUME_YES is set or stdin is not a
# TTY — the priority order install_nano.sh already follows.

# Decode one keypress into _KEY (and _KEYCH for digits). Bash 3.2 safe:
# no read -N, no fractional -t. Arrows arrive as ESC then "[A"/"OA".
_read_key() {
    local k s
    _KEY=""; _KEYCH=""
    IFS= read -rsn1 k || { _KEY="QUIT"; return 0; }
    if [[ -z "$k" ]]; then _KEY="ENTER"; return 0; fi
    case "$k" in
        $'\r'|$'\n') _KEY="ENTER" ;;
        $'\x1b')
            s=""
            IFS= read -rsn2 -t 1 s
            case "$s" in
                '[A'|'OA') _KEY="UP" ;;
                '[B'|'OB') _KEY="DOWN" ;;
                '')        _KEY="QUIT" ;;
                *)         _KEY="OTHER" ;;
            esac ;;
        [0-9]) _KEY="DIGIT"; _KEYCH="$k" ;;
        k|K)   _KEY="UP" ;;
        j|J)   _KEY="DOWN" ;;
        q|Q)   _KEY="QUIT" ;;
        *)     _KEY="OTHER" ;;
    esac
    return 0
}

# ask_confirm "question" [Y|N]  ->  exit 0 for yes, 1 for no
ask_confirm() {
    local q="$1" def="${2:-N}" hint reply
    if [[ -n "${ASSUME_YES:-}" ]]; then return 0; fi
    if [[ ! -t 0 ]]; then [[ "$def" == "Y" ]]; return $?; fi
    if [[ "$def" == "Y" ]]; then hint="Y/n"; else hint="y/N"; fi
    _log_line "$QOL_STEP" ASK "$q" >&2
    printf '    %s❯%s %s[%s]%s ' "$QOL_PASS" "$QOL_RESET" "$QOL_META" "$hint" "$QOL_RESET" >&2
    read -r reply
    reply="${reply:-$def}"
    case "$reply" in [Yy]*) return 0 ;; *) return 1 ;; esac
}

# ask_value "question" "default" ["hint"]  ->  echoes the answer
ask_value() {
    local q="$1" def="$2" hint="${3:-}" reply
    if [[ -n "${ASSUME_YES:-}" || ! -t 0 ]]; then printf '%s' "$def"; return 0; fi
    _log_line "$QOL_STEP" ASK "$q" >&2
    [[ -n "$hint" ]] && printf '         %s%s%s\n' "$QOL_META" "$hint" "$QOL_RESET" >&2
    printf '    %s❯%s [%s%s%s] ' "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$def" "$QOL_RESET" >&2
    read -r reply
    printf '%s' "${reply:-$def}"
}

# Draw the choice list. Emits exactly (count + 3) lines so the caller knows
# how far to move the cursor back up when redrawing.
_ask_choice_draw() {
    local heading="$1" sel="$2"; shift 2
    local i=0 item label hint plain pad cols
    cols="$(_term_cols)"
    printf '\n %s%s%s%s\n' "$QOL_BOLD" "$QOL_STEP" "$heading" "$QOL_RESET"
    for item in "$@"; do
        label="${item%%|*}"
        hint="${item#*|}"; [[ "$hint" == "$item" ]] && hint=""
        # Pad every row out to the full width with real spaces. The selection
        # bar has to reach the right edge, and CLR_EOL cannot carry it there:
        # screen and tmux report no `bce`, so ESC[K erases to the default
        # background and cuts the bar off where the text ended. Padding the
        # unselected rows is what paints over the bar as it moves away.
        # Three leading columns in both branches: " ❯ " when selected, three
        # spaces when not. Measure the same shape the row actually prints.
        printf -v plain '   %2d   %-18s %s' "$(( i + 1 ))" "$label" "$hint"
        pad=$(( cols - ${#plain} ))
        (( pad < 0 )) && pad=0
        if (( i == sel )); then
            printf '%s%s%s ❯ %2d   %-18s %s%*s%s\n' \
                "$QOL_SEL" "$QOL_BOLD" "$QOL_PASS" "$(( i + 1 ))" "$label" "$hint" \
                "$pad" '' "$QOL_RESET"
        else
            printf '   %s%2d%s   %s%-18s%s %s%s%s%*s\n' \
                "$QOL_META" "$(( i + 1 ))" "$QOL_RESET" \
                "$QOL_FG" "$label" "$QOL_RESET" "$QOL_META" "$hint" "$QOL_RESET" \
                "$pad" ''
        fi
        i=$(( i + 1 ))
    done
    printf ' %s↑/↓%s or %sj/k%s move   %s1-9%s jump   %s⏎%s select\n' \
        "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$QOL_RESET" \
        "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$QOL_RESET"
}

# ask_choice "HEADING" default_index "label|hint" [...]  ->  echoes 1-based index
# Redraws in place rather than taking the alternate screen: an installer that
# blanks the scrollback has destroyed the record of what it just did.
ask_choice() {
    local heading="$1" def="$2"; shift 2
    local n=$#
    local sel=$(( def - 1 ))
    if [[ -n "${ASSUME_YES:-}" || ! -t 0 ]]; then printf '%s' "$def"; return 0; fi
    _ask_choice_draw "$heading" "$sel" "$@" >&2
    while true; do
        _read_key
        case "$_KEY" in
            ENTER) break ;;
            QUIT)  sel=$(( def - 1 )); break ;;
            UP)    sel=$(( (sel - 1 + n) % n )) ;;
            DOWN)  sel=$(( (sel + 1) % n )) ;;
            DIGIT) if (( 10#$_KEYCH >= 1 && 10#$_KEYCH <= n )); then sel=$(( 10#$_KEYCH - 1 )); fi ;;
        esac
        printf '\033[%dA' $(( n + 3 )) >&2
        _ask_choice_draw "$heading" "$sel" "$@" >&2
    done
    printf '%s' "$(( sel + 1 ))"
}
# ‒‒ end theme block

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Safety
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
handle_ctrl_c() {
    echo
    log_err "Interrupted. Exiting."
    exit 130
}
trap handle_ctrl_c INT

handle_err() {
    local exit_code=$?
    log_err "Error on line $1 (exit $exit_code). Aborting."
    exit "$exit_code"
}
trap 'handle_err $LINENO' ERR

check_for_root() {
    if [[ $EUID -eq 0 ]]; then
        log_err "Do not run as root. You'll be prompted for sudo if needed."
        exit 1
    fi
}

usage() {
    cat <<'USAGE'
Usage: uninstall_omz_p10k.sh [options]

Removes Oh My Zsh and Powerlevel10k, and strips their lines out of ~/.zshrc.
Your own .zshrc content is preserved and the file is backed up first.

Options:
  -n, --dry-run   Print exactly what would be removed, then exit. No changes.
  -y, --yes       Skip the confirmation prompt.
  -h, --help      Show this help.
USAGE
}

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --yes|-y)     ASSUME_YES=1 ;;
            --dry-run|-n) DRY_RUN=1 ;;
            --help|-h)    usage; exit 0 ;;
            *)            log_err "Unknown option: $1"; usage; exit 1 ;;
        esac
        shift
    done
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Detection
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Populates FOUND_PATHS / FOUND_ZSHRC / FOUND_BREW.
# Returns non-zero when there is nothing to do.
omz_p10k_present() {
    FOUND_PATHS=()
    FOUND_ZSHRC=""
    FOUND_BREW=()

    local p
    for p in "$OMZ_DIR" "$P10K_RC" "$HOME/.cache/gitstatus" "$HOME/.cache/p10k-$USER"; do
        [[ -e "$p" ]] && FOUND_PATHS+=("$p")
    done
    # Globs that may match nothing; the -e test filters the literal pattern out.
    for p in "$HOME"/.cache/p10k-*.zsh "$HOME"/.cache/p10k-*.zsh.zwc "$HOME"/.zcompdump*; do
        [[ -e "$p" ]] && FOUND_PATHS+=("$p")
    done

    if [[ -f "$ZSHRC" ]] && grep -qE 'oh-my-zsh|p10k|powerlevel10k|POWERLEVEL9K|ZSH_THEME' "$ZSHRC"; then
        FOUND_ZSHRC=1
    fi

    if [[ "$OS" == "Darwin" ]] && command -v brew &>/dev/null; then
        brew list --formula powerlevel10k &>/dev/null && FOUND_BREW+=("powerlevel10k")
        brew list --cask font-meslo-for-powerlevel10k &>/dev/null \
            && FOUND_BREW+=("--cask font-meslo-for-powerlevel10k")
    fi

    [[ "${#FOUND_PATHS[@]}" -gt 0 || -n "$FOUND_ZSHRC" || "${#FOUND_BREW[@]}" -gt 0 ]]
}

# Detail lines under a milestone are indented to column 10, where the badge's
# message text starts, so the plan reads as one block with the INFO above it.
plan_line() { printf '         %s\n' "$1"; }

print_plan() {
    log_phase "PLAN"
    log_info "The following will be removed:"
    local p
    for p in "${FOUND_PATHS[@]}"; do
        plan_line "rm -rf  $p"
    done
    for p in "${FOUND_BREW[@]}"; do
        plan_line "brew uninstall $p"
    done
    if [[ -n "$FOUND_ZSHRC" ]]; then
        plan_line "edit    $ZSHRC  (these lines):"
        grep -nE 'oh-my-zsh|p10k|powerlevel10k|POWERLEVEL9K|ZSH_THEME|^plugins=' "$ZSHRC" \
            | sed 's/^/             /'
    fi
    log_info "A timestamped backup of $ZSHRC is taken before any edit."
}

# 0 = proceed, 1 = user kept the install, 130 = user quit.
#
# Not ask_confirm: this is a three-way question (remove / keep / quit) and the
# 130 return is what tells a sourcing caller to abort. Borrow the shape of
# ask_confirm's prompt — ASK badge, then a jade caret — without its semantics.
confirm_removal() {
    [[ -n "$ASSUME_YES" ]] && return 0
    local answer=""
    while true; do
        log_ask "Remove Oh My Zsh and Powerlevel10k?"
        printf '    %s❯%s %s[y = remove / n = keep / q = quit]%s ' \
            "$QOL_PASS" "$QOL_RESET" "$QOL_META" "$QOL_RESET"
        read -r answer
        case "$answer" in
            [Yy]) return 0 ;;
            [Nn])
                log_info "Uninstall cancelled. Nothing was changed."
                return 1
                ;;
            [Qq])
                log_warn "Quitting at user request."
                return 130
                ;;
            *) log_warn "Invalid input: '$answer' (expected y, n, or q)." ;;
        esac
    done
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# .zshrc surgery
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
backup_zshrc() {
    local backup
    backup="$ZSHRC.pre-starship.$(date +%Y%m%d-%H%M%S).bak"
    cp "$ZSHRC" "$backup"
    printf '%s\n' "$backup"
}

# Overwrite dst with the contents of src, keeping dst's mode, owner and inode.
# `mv tmp dst` would be simpler but carries the temp file's permissions across —
# mktemp creates 0600, so that silently tightens a normal 0644 .zshrc.
replace_file_contents() {
    local src="$1" dst="$2"
    cat "$src" > "$dst"
    rm -f "$src"
}

# Remove every Oh My Zsh / Powerlevel10k line from the given file.
#
# Comments are handled as *runs*, not as individual lines. The Oh My Zsh .zshrc
# template is mostly multi-line commentary, and deleting only the lines that
# happen to say "oh-my-zsh" leaves behind half-sentences like
#   "# Set name of the theme to load --- if set to "random", it will"
# So: any unbroken run of comment lines that mentions Oh My Zsh or Powerlevel10k
# anywhere within it is dropped whole. A short list of verbatim template lines
# that carry no such marker ("# User configuration") is matched exactly.
#
# Two multi-line code constructs need state machines: the p10k instant-prompt
# `if` block and the `plugins=( ... )` array.
strip_zshrc() {
    local file="$1" tmp tmp2
    tmp="$(mktemp)"
    tmp2="$(mktemp)"

    awk '
        function flush_run(   i) {
            if (run_n && !run_drop) { for (i = 1; i <= run_n; i++) print run[i] }
            run_n = 0
            run_drop = 0
        }

        BEGIN {
            # Any of these inside a comment run condemns the whole run.
            markers = "oh-my-zsh|ohmyzsh|Oh My Zsh|p10k|Powerlevel10k|POWERLEVEL9K" \
                      "|ZSH_THEME|ZSH_CUSTOM|[$]ZSH/|plugins=\\(|CASE_SENSITIVE" \
                      "|HYPHEN_INSENSITIVE|DISABLE_MAGIC_FUNCTIONS|DISABLE_LS_COLORS" \
                      "|DISABLE_AUTO_TITLE|ENABLE_CORRECTION|COMPLETION_WAITING_DOTS" \
                      "|DISABLE_UNTRACKED_FILES_DIRTY|HIST_STAMPS|DISABLE_AUTO_UPDATE" \
                      "|ZSH_COMPDUMP|RANDOM_THEME|:omz:|auto-update"
            # Verbatim Oh My Zsh template comment lines with no marker of their own.
            phrases = "^[[:space:]]*#[[:space:]]*(If you come from bash you might have to change your [$]PATH" \
                      "|export PATH=[$]HOME/bin:|User configuration$|export MANPATH=" \
                      "|You may need to manually set your language environment|export LANG=" \
                      "|Compilation flags$|export ARCHFLAGS=|Example aliases$|alias zshconfig=" \
                      "|Add wisely, as too many plugins slow down shell startup)"
        }

        # --- p10k instant prompt if/fi block ----------------------------------
        /^[[:space:]]*if[[:space:]]*\[\[[[:space:]]*-r[[:space:]].*p10k-instant-prompt/ {
            flush_run(); in_ip = 1; next
        }
        in_ip { if ($0 ~ /^[[:space:]]*fi[[:space:]]*$/) { in_ip = 0 } next }

        # --- plugins=( ... ), single- or multi-line ---------------------------
        /^[[:space:]]*plugins=\(/ { flush_run(); if ($0 !~ /\)/) { in_plugins = 1 } next }
        in_plugins { if ($0 ~ /\)/) { in_plugins = 0 } next }

        # --- comment runs -----------------------------------------------------
        /^[[:space:]]*#/ {
            run[++run_n] = $0
            if ($0 ~ markers || $0 ~ phrases) { run_drop = 1 }
            next
        }
        { flush_run() }

        # --- single-line code removals ----------------------------------------
        /powerlevel10k\.zsh-theme/                            { next }
        /^[[:space:]]*(export[[:space:]]+)?ZSH=.*oh-my-zsh/   { next }
        /^[[:space:]]*ZSH_THEME(_RANDOM_CANDIDATES)?=/        { next }
        /^[[:space:]]*source[[:space:]]+\$ZSH\/oh-my-zsh\.sh/ { next }
        /source[[:space:]]+.*\.p10k\.zsh/                     { next }
        /^[[:space:]]*zstyle[[:space:]]+.:omz:/               { next }
        /^[[:space:]]*fpath\+=.*oh-my-zsh/                    { next }
        /^[[:space:]]*(export[[:space:]]+)?ZSH_CUSTOM=/       { next }
        /^[[:space:]]*(typeset[[:space:]]+-g[[:space:]]+)?POWERLEVEL9K_/ { next }

        { print }
        END { flush_run() }
    ' "$file" > "$tmp"

    # Removal leaves 5-10 line gaps where the Oh My Zsh comment blocks were.
    # Collapse every run of blank lines to one, and drop leading blanks.
    awk '
        /^[[:space:]]*$/ { blanks++; next }
        { if (started && blanks) print ""; started = 1; blanks = 0; print }
    ' "$tmp" > "$tmp2"

    replace_file_contents "$tmp2" "$file"
    rm -f "$tmp"
}

verify_zshrc() {
    local file="$1"
    command -v zsh &>/dev/null || { log_warn "zsh not found; skipping syntax check."; return 0; }
    zsh -n "$file" 2>/dev/null
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Removal
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
remove_paths() {
    log_step "Removing Oh My Zsh and Powerlevel10k files..."
    local p
    for p in "${FOUND_PATHS[@]}"; do
        rm -rf "$p"
        plan_line "removed  $p"
    done
    log_ok "${#FOUND_PATHS[@]} path(s) removed."
}

remove_brew_packages() {
    [[ "$OS" == "Darwin" ]] || return 0
    [[ "${#FOUND_BREW[@]}" -gt 0 ]] || return 0
    command -v brew &>/dev/null || return 0

    log_step "Removing Homebrew packages..."
    if brew list --formula powerlevel10k &>/dev/null; then
        brew uninstall powerlevel10k || log_warn "brew uninstall powerlevel10k failed; continuing."
    fi
    # font-meslo-lg-nerd-font and font-symbols-only-nerd-font are deliberately
    # left alone — Starship uses them.
    if brew list --cask font-meslo-for-powerlevel10k &>/dev/null; then
        brew uninstall --cask font-meslo-for-powerlevel10k \
            || log_warn "brew uninstall of the p10k Meslo cask failed; continuing."
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Entry point (also the sourceable API)
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# The run bookends live in the run-directly branch below, not here: when
# another script sources this file and calls the function, that run already has
# a banner and owns its own ending.
uninstall_omz_p10k() {
    # NOTHING_DONE is read by the run-directly branch, which must not print a
    # "REMOVED" completion block for a run that removed nothing.
    if ! omz_p10k_present; then
        log_ok "Oh My Zsh and Powerlevel10k are not installed. Nothing to remove."
        NOTHING_DONE="not installed"
        return 0
    fi

    print_plan

    if [[ -n "$DRY_RUN" ]]; then
        log_ok "Dry run — nothing above was actually removed."
        NOTHING_DONE="dry run"
        return 0
    fi

    local rc=0
    confirm_removal || rc=$?
    # 'n' means keep the install: that is a successful no-op, not a failure.
    [[ "$rc" -eq 1 ]] && { NOTHING_DONE="cancelled"; return 0; }
    [[ "$rc" -eq 0 ]] || return "$rc"

    # .zshrc goes first: it is the only step that can fail recoverably, and
    # nothing has been deleted yet if it does.
    local backup=""
    if [[ -n "$FOUND_ZSHRC" ]]; then
        log_phase "ZSHRC"
        log_step "Editing $ZSHRC..."
        backup="$(backup_zshrc)"
        plan_line "backup   $backup"
        strip_zshrc "$ZSHRC"
        if ! verify_zshrc "$ZSHRC"; then
            log_err "The edited $ZSHRC failed 'zsh -n'. Restoring the backup; nothing else was removed."
            cp "$backup" "$ZSHRC"
            return 1
        fi
        log_ok "$ZSHRC cleaned."
    fi

    log_phase "REMOVAL"
    remove_paths
    remove_brew_packages

    log_ok "Oh My Zsh and Powerlevel10k have been removed."
    # Read by the run-directly branch to add a NEXT line pointing at the backup.
    RESTORE_BACKUP="$backup"
    log_info "Gone with Oh My Zsh: its git aliases (gst, gco, ...), its fzf keybindings"
    log_info "(ctrl-R / ctrl-T), and the zsh-autosuggestions, zsh-syntax-highlighting and"
    log_info "zsh-completions plugins it hosted. install_zsh_starship.sh restores"
    log_info "equivalents for all of them."
    return 0
}

# When executed directly (not sourced), parse flags and run.
# The `|| rc=$?` is load-bearing: a bare call would let the ERR trap fire on the
# expected non-zero returns (130 when the user quits) and print a spurious error.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    check_for_root
    parse_args "$@"
    banner "OH MY ZSH + P10K UNINSTALLER" "files · brew · .zshrc"
    UNINSTALL_RC=0
    RESTORE_BACKUP=""
    NOTHING_DONE=""
    uninstall_omz_p10k || UNINSTALL_RC=$?
    if [[ "$UNINSTALL_RC" -eq 0 && -z "$NOTHING_DONE" ]]; then
        log_complete "OH MY ZSH + P10K REMOVED"
        [[ -n "$RESTORE_BACKUP" ]] && log_next "Your previous .zshrc:  $RESTORE_BACKUP"
        log_next "Open a new shell to pick up the cleaned .zshrc."
        log_next "For a Starship prompt with the same conveniences:  ./install_zsh_starship.sh"
        echo
    elif [[ "$UNINSTALL_RC" -eq 0 ]]; then
        # A run that changed nothing still ended cleanly; say which kind it was
        # rather than claiming a removal that did not happen.
        log_complete "NOTHING REMOVED ($NOTHING_DONE)"
        [[ "$NOTHING_DONE" == "dry run" ]] && log_next "Run it for real:  ./uninstall_omz_p10k.sh"
        echo
    fi
    exit "$UNINSTALL_RC"
fi
