#!/usr/bin/env bash
# Proves every copy of the theme block in this repo has not drifted from the
# canonical one in linux/base_functions.sh.
#
# Five scripts embed the full theme block because they must run on macOS, where
# linux/base_functions.sh is unavailable. netstatus.sh embeds only the generated
# ink block: it is sourced into interactive login shells and prints a one-line
# readout, so it needs the palette but none of the badge grammar around it.
#
# This test is the only thing keeping those copies honest. Run it after touching
# any of them, and after `build-design-tokens.py --write-qol` in the vault.
#
# Run: ./tests/test-theme-sync.sh
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIB="$ROOT/linux/base_functions.sh"

# Scripts carrying the whole theme block: qol_init_color through the end marker.
FULL_COPIES=(
    "install_zsh_starship.sh"
    "install_nano.sh"
    "install_zsh.sh"
    "uninstall_omz_p10k.sh"
    "macos/install-nerd-fonts.sh"
)

# Scripts carrying only the generated ink block, between the two markers.
INK_COPIES=(
    "netstatus.sh"
)

TESTS_RUN=0
TESTS_FAILED=0

extract_theme() { sed -n '/^qol_init_color() {/,/^# ‒‒ end theme block/p' "$1"; }
extract_ink()   { sed -n '/^# ‒‒ generated by dojobrain/,/^# ‒‒ end generated block/p' "$1"; }

# compare <what> <extractor> <canonical-text> <relative-path>
compare() {
    local what="$1" extractor="$2" want="$3" rel="$4"
    local path="$ROOT/$rel" got
    TESTS_RUN=$((TESTS_RUN + 1))

    if [[ ! -f "$path" ]]; then
        TESTS_FAILED=$((TESTS_FAILED + 1))
        printf '  FAIL %s: file not found\n' "$rel"
        return
    fi

    got="$("$extractor" "$path")"
    if [[ -z "$got" ]]; then
        TESTS_FAILED=$((TESTS_FAILED + 1))
        printf '  FAIL %s: no %s found\n' "$rel" "$what"
        return
    fi
    if [[ "$want" == "$got" ]]; then
        printf '  ok   %s: %s matches base_functions.sh\n' "$rel" "$what"
        return
    fi

    TESTS_FAILED=$((TESTS_FAILED + 1))
    printf '  FAIL %s: %s has drifted\n' "$rel" "$what"
    diff <(printf '%s\n' "$want") <(printf '%s\n' "$got") | sed 's/^/       /'
}

CANON_THEME="$(extract_theme "$LIB")"
CANON_INK="$(extract_ink "$LIB")"

if [[ -z "$CANON_THEME" ]]; then
    printf 'FAIL no theme block found in %s — nothing to compare against\n' "$LIB"
    exit 1
fi
if [[ -z "$CANON_INK" ]]; then
    printf 'FAIL no generated ink block found in %s — nothing to compare against\n' "$LIB"
    exit 1
fi

printf '\nfull theme block (%d lines)\n' "$(printf '%s\n' "$CANON_THEME" | wc -l | tr -d ' ')"
for rel in "${FULL_COPIES[@]}"; do
    compare "theme block" extract_theme "$CANON_THEME" "$rel"
done

printf '\ngenerated ink block only (%d lines)\n' "$(printf '%s\n' "$CANON_INK" | wc -l | tr -d ' ')"
for rel in "${INK_COPIES[@]}"; do
    compare "ink block" extract_ink "$CANON_INK" "$rel"
done

printf '\n%d run, %d failed\n' "$TESTS_RUN" "$TESTS_FAILED"
[[ "$TESTS_FAILED" -eq 0 ]]
