# shellcheck shell=bash
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# base_functions.sh
#
# Shared helper library for the scripts in this repo.
# This file is meant to be SOURCED, not executed:
#     source base_functions.sh
#
# Provides:
#   - The repo-standard output theme: printline, style_text, format_font and
#     the log_info / log_step / log_ok / log_warn / log_err / log_title
#     helpers. Keep the theme in sync with install_zsh_starship.sh (standalone).
#   - fstring: back-compat wrapper around the old output API.
#   - check_status, as_root, not_as_root, check_if_linux
#   - apt helpers: update_repo, update_and_upgrade, install_packages
#   - OS_NAME / OS_VERSION / OS_CODENAME exported from /etc/os-release
#   - A CTRL-C trap (installed at the bottom of this file)
#
# NOTE: Several functions call `exit` on error. Because this file is meant to
# be sourced by scripts, that terminates the *calling* script. That is
# intentional — but do not source this into an interactive shell and then
# call e.g. `as_root` unless you're prepared to have the shell exit.
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Pretty output — IT Dojo terminal design system
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Palette and rules:
#   ~/vaults/dojobrain/30-references/design-system/itdojo-terminal-design-system.md
# The ink case block below is GENERATED. Re-emit it rather than hand-editing:
#   cd ~/vaults/dojobrain && uv run scripts/build-design-tokens.py --emit-bash
# Keep this whole section byte-identical to the copy in install_zsh_starship.sh.

# Decide color and depth once. Re-callable so tests can force a tier.
#   NO_COLOR         — set to disable color entirely (wins over everything)
#   QOL_FORCE_COLOR  — set to keep color when stdout is not a TTY (e.g. less -R)
#   QOL_COLOR_DEPTH  — truecolor (default) | 256 | 8 | none
# Several inks have no reader in any one script that carries this block —
# a token ink with no consumer is suppressed, not deleted, because dropping a
# color from a palette copy makes it a worse copy.
# shellcheck disable=SC2034
qol_init_color() {
    if [[ -n "${NO_COLOR:-}" ]]; then
        QOL_COLOR=""
    elif [[ -n "${QOL_FORCE_COLOR:-}" || -t 1 ]]; then
        QOL_COLOR=1
    else
        QOL_COLOR=""
    fi

    case "${QOL_COLOR_DEPTH:-truecolor}" in
        256)  QOL_DEPTH=256 ;;
        8)    QOL_DEPTH=8 ;;
        none) QOL_DEPTH=none ;;
        *)    QOL_DEPTH=truecolor ;;
    esac
    [[ -z "$QOL_COLOR" ]] && QOL_DEPTH=none

# ‒‒ generated by dojobrain scripts/build-design-tokens.py --emit-bash
# ‒‒ do not hand-edit; edit tokens/colors.css and re-emit.
    case "$QOL_DEPTH" in
        truecolor)
            QOL_STEP=$'\033[38;2;188;176;232m'
            QOL_PASS=$'\033[38;2;78;206;106m'
            QOL_INFO=$'\033[38;2;122;160;216m'
            QOL_WARN=$'\033[38;2;224;180;90m'
            QOL_STOP=$'\033[38;2;224;107;130m'
            QOL_FG=$'\033[38;2;228;222;245m'
            QOL_META=$'\033[38;2;154;147;181m'
            QOL_RULE=$'\033[38;2;74;65;112m'
            QOL_SEL=$'\033[48;2;36;29;61m'
            QOL_OKBG=$'\033[48;2;21;50;31m'
            ;;
        256)
            QOL_STEP=$'\033[38;5;140m'
            QOL_PASS=$'\033[38;5;77m'
            QOL_INFO=$'\033[38;5;110m'
            QOL_WARN=$'\033[38;5;179m'
            QOL_STOP=$'\033[38;5;168m'
            QOL_FG=$'\033[38;5;189m'
            QOL_META=$'\033[38;5;103m'
            QOL_RULE=$'\033[38;5;60m'
            QOL_SEL=$'\033[48;5;235m'
            QOL_OKBG=$'\033[48;5;22m'
            ;;
        8)
            QOL_STEP=$'\033[94m'
            QOL_PASS=$'\033[92m'
            QOL_INFO=$'\033[94m'
            QOL_WARN=$'\033[93m'
            QOL_STOP=$'\033[91m'
            QOL_FG=$'\033[97m'
            QOL_META=$'\033[90m'
            QOL_RULE=$'\033[90m'
            QOL_SEL=$'\033[7m'
            QOL_OKBG=$'\033[7m'
            ;;
        *)
            QOL_STEP="" QOL_PASS="" QOL_INFO="" QOL_WARN="" QOL_STOP="" QOL_FG="" QOL_META="" QOL_RULE="" QOL_SEL="" QOL_OKBG=""
            ;;
    esac
# ‒‒ end generated block

    if [[ "$QOL_DEPTH" == "none" ]]; then
        QOL_BOLD="" QOL_DIM="" QOL_RESET=""
    else
        QOL_BOLD=$'\033[1m'; QOL_DIM=$'\033[2m'; QOL_RESET=$'\033[0m'
    fi
}
qol_init_color

# Terminal width, falling back to 80 with no TTY (cron, CI, pipes).
#
# Ask the terminal, not terminfo. `tput cols 2>/dev/null` inside a command
# substitution answers 80 however wide the window is: with stdout captured,
# ncurses reads the window size off stderr instead, and that redirect throws
# the only usable fd away. Every rule, bookend and selection bar in this file
# was pinned to 80 columns by it. stty asks /dev/tty directly, so no amount of
# nesting can hide the answer. COLUMNS still wins when set, as an override.
_term_cols() {
    local cols="${COLUMNS:-}"
    if [[ ! "$cols" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
        cols="$(stty size </dev/tty 2>/dev/null | cut -d' ' -f2)"
    fi
    if [[ ! "$cols" =~ ^[0-9]+$ ]] || (( cols <= 0 )); then
        cols=80
    fi
    printf '%s' "$cols"
}

# Repeat a character n times. Emits nothing for n <= 0.
_repeat() {
    local ch="$1" n="$2" line
    [[ "$n" =~ ^-?[0-9]+$ ]] || return 0
    (( n <= 0 )) && return 0
    printf -v line '%*s' "$n" ''
    printf '%s' "${line// /$ch}"
}

# One milestone line. The prefix is exactly 9 columns: gutter, space,
# 4-char badge, 3 spaces. Message text therefore starts at column 10.
_log_line() {
    local ink="$1" badge="$2" text="$3"
    printf '%s%s▌ %-4s   %s%s\n' "$QOL_BOLD" "$ink" "$badge" "$text" "$QOL_RESET"
}

log_step() { _log_line "$QOL_STEP" STEP "$1"; }
log_ok()   { _log_line "$QOL_PASS" PASS "$1"; }
log_info() { _log_line "$QOL_INFO" INFO "$1"; }
log_warn() { _log_line "$QOL_WARN" WARN "$1"; }
log_err()  { _log_line "$QOL_STOP" STOP "$1" >&2; }
log_ask()  { _log_line "$QOL_STEP" ASK  "$1"; }
log_next() { _log_line "$QOL_INFO" NEXT "$1"; }

# Phase boundary: a gray rule carrying the phase name in violet. A rule now
# means "new phase", which is information; a rule per line meant nothing.
log_phase() {
    local title="$1" cols fill
    cols="$(_term_cols)"
    fill=$(( cols - ${#title} - 4 ))
    printf '\n%s──%s %s%s%s%s %s%s\n\n' \
        "$QOL_RULE" "$QOL_RESET" \
        "$QOL_BOLD$QOL_STEP" "$title" "$QOL_RESET" \
        "$QOL_RULE" "$(_repeat '─' "$fill")" "$QOL_RESET"
}

# Run bookends. Jade rules, so a run's edges are findable when scrolling
# back through screens of package-manager output; phase rules are gray.
banner() {
    local title="$1" sub="${2:-}" cols
    cols="$(_term_cols)"
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    printf '  %s%s⛩ %s ⛩%s' "$QOL_BOLD" "$QOL_PASS" "$title" "$QOL_RESET"
    [[ -n "$sub" ]] && printf '   %s%s%s' "$QOL_META" "$sub" "$QOL_RESET"
    printf '\n%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# NOTE: not named `complete` — that is a bash builtin.
log_complete() {
    local title="$1" cols
    cols="$(_term_cols)"
    printf '\n%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    printf '  %s%s%s ⛩ %s ⛩ %s\n' "$QOL_OKBG" "$QOL_BOLD" "$QOL_PASS" "$title" "$QOL_RESET"
    printf '%s%s%s\n\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# ‒‒ Back-compat ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Eight other scripts call these. Kept working, not kept identical: printline
# no longer appears in any log_* line, because the design uses phase rules.

# Print a separator line the width of the terminal.
# Usage: printline [solid|bullet|ibeam|star|plus|diamond|dentistry]
printline() {
    local sep
    case "${1:-solid}" in
        bullet)    sep="•" ;;
        ibeam)     sep="⌶" ;;
        star)      sep="★" ;;
        plus)      sep="✛" ;;
        diamond)   sep="◆" ;;
        dentistry) sep="⏥" ;;
        *)         sep="─" ;;
    esac
    printf '%s%s%s\n' "$QOL_RULE" "$(_repeat "$sep" "$(_term_cols)")" "$QOL_RESET"
}

# Print styled text with no separator. Also usable inline via command
# substitution: echo "I am a $(style_text "Raspberry Pi" bold wine)."
# Usage: style_text "text" [normal|bold|light] [brand or legacy color name]
# Brand names:  violet jade steel saffron wine prose meta rule
# Legacy names: blue   green  —     yellow  red   —     —    —
style_text() {
    local text="$1" weight="${2:-normal}" color="${3:-}"
    local wt="" ink=""
    case "$weight" in
        bold)  wt="$QOL_BOLD" ;;
        light) wt="$QOL_DIM" ;;
    esac
    case "$color" in
        violet)        ink="$QOL_STEP" ;;
        jade|green)    ink="$QOL_PASS" ;;
        steel|blue)    ink="$QOL_INFO" ;;
        saffron|yellow) ink="$QOL_WARN" ;;
        wine|red)      ink="$QOL_STOP" ;;
        prose)         ink="$QOL_FG" ;;
        meta)          ink="$QOL_META" ;;
        rule)          ink="$QOL_RULE" ;;
    esac
    if [[ -z "$QOL_COLOR" ]] || [[ -z "$ink" && -z "$wt" ]]; then
        printf '%s\n' "$text"
        return 0
    fi
    printf '%s%s%s%s\n' "$wt" "$ink" "$text" "$QOL_RESET"
}

# Separator + styled text. Retained for callers that predate log_phase;
# new code should use log_phase or a log_* helper instead.
format_font() {
    printline
    style_text "$1" "${2:-bold}" "${3:-saffron}"
}

# Banner for script titles. Prefer banner/log_complete in new code.
log_title() {
    local cols
    cols="$(_term_cols)"
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
    style_text "$1" bold jade
    printf '%s%s%s\n' "$QOL_PASS" "$(_repeat '━' "$cols")" "$QOL_RESET"
}

# ‒‒ Interactive ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Three question shapes, sharing gotime's chrome. Prompts go to stderr so
# ask_value and ask_choice can be captured with $(...). All three skip the
# prompt and return the default when ASSUME_YES is set or stdin is not a
# TTY — the priority order install_nano.sh already follows.

# Decode one keypress into _KEY (and _KEYCH for digits). Bash 3.2 safe:
# no read -N, no fractional -t. Arrows arrive as ESC then "[A"/"OA".
_read_key() {
    local k s
    _KEY=""; _KEYCH=""
    IFS= read -rsn1 k || { _KEY="QUIT"; return 0; }
    if [[ -z "$k" ]]; then _KEY="ENTER"; return 0; fi
    case "$k" in
        $'\r'|$'\n') _KEY="ENTER" ;;
        $'\x1b')
            s=""
            IFS= read -rsn2 -t 1 s
            case "$s" in
                '[A'|'OA') _KEY="UP" ;;
                '[B'|'OB') _KEY="DOWN" ;;
                '')        _KEY="QUIT" ;;
                *)         _KEY="OTHER" ;;
            esac ;;
        [0-9]) _KEY="DIGIT"; _KEYCH="$k" ;;
        k|K)   _KEY="UP" ;;
        j|J)   _KEY="DOWN" ;;
        q|Q)   _KEY="QUIT" ;;
        *)     _KEY="OTHER" ;;
    esac
    return 0
}

# ask_confirm "question" [Y|N]  ->  exit 0 for yes, 1 for no
ask_confirm() {
    local q="$1" def="${2:-N}" hint reply
    if [[ -n "${ASSUME_YES:-}" ]]; then return 0; fi
    if [[ ! -t 0 ]]; then [[ "$def" == "Y" ]]; return $?; fi
    if [[ "$def" == "Y" ]]; then hint="Y/n"; else hint="y/N"; fi
    _log_line "$QOL_STEP" ASK "$q" >&2
    printf '    %s❯%s %s[%s]%s ' "$QOL_PASS" "$QOL_RESET" "$QOL_META" "$hint" "$QOL_RESET" >&2
    read -r reply
    reply="${reply:-$def}"
    case "$reply" in [Yy]*) return 0 ;; *) return 1 ;; esac
}

# ask_value "question" "default" ["hint"]  ->  echoes the answer
ask_value() {
    local q="$1" def="$2" hint="${3:-}" reply
    if [[ -n "${ASSUME_YES:-}" || ! -t 0 ]]; then printf '%s' "$def"; return 0; fi
    _log_line "$QOL_STEP" ASK "$q" >&2
    [[ -n "$hint" ]] && printf '         %s%s%s\n' "$QOL_META" "$hint" "$QOL_RESET" >&2
    printf '    %s❯%s [%s%s%s] ' "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$def" "$QOL_RESET" >&2
    read -r reply
    printf '%s' "${reply:-$def}"
}

# Draw the choice list. Emits exactly (count + 3) lines so the caller knows
# how far to move the cursor back up when redrawing.
_ask_choice_draw() {
    local heading="$1" sel="$2"; shift 2
    local i=0 item label hint plain pad cols
    cols="$(_term_cols)"
    printf '\n %s%s%s%s\n' "$QOL_BOLD" "$QOL_STEP" "$heading" "$QOL_RESET"
    for item in "$@"; do
        label="${item%%|*}"
        hint="${item#*|}"; [[ "$hint" == "$item" ]] && hint=""
        # Pad every row out to the full width with real spaces. The selection
        # bar has to reach the right edge, and CLR_EOL cannot carry it there:
        # screen and tmux report no `bce`, so ESC[K erases to the default
        # background and cuts the bar off where the text ended. Padding the
        # unselected rows is what paints over the bar as it moves away.
        # Three leading columns in both branches: " ❯ " when selected, three
        # spaces when not. Measure the same shape the row actually prints.
        printf -v plain '   %2d   %-18s %s' "$(( i + 1 ))" "$label" "$hint"
        pad=$(( cols - ${#plain} ))
        (( pad < 0 )) && pad=0
        if (( i == sel )); then
            printf '%s%s%s ❯ %2d   %-18s %s%*s%s\n' \
                "$QOL_SEL" "$QOL_BOLD" "$QOL_PASS" "$(( i + 1 ))" "$label" "$hint" \
                "$pad" '' "$QOL_RESET"
        else
            printf '   %s%2d%s   %s%-18s%s %s%s%s%*s\n' \
                "$QOL_META" "$(( i + 1 ))" "$QOL_RESET" \
                "$QOL_FG" "$label" "$QOL_RESET" "$QOL_META" "$hint" "$QOL_RESET" \
                "$pad" ''
        fi
        i=$(( i + 1 ))
    done
    printf ' %s↑/↓%s or %sj/k%s move   %s1-9%s jump   %s⏎%s select\n' \
        "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$QOL_RESET" \
        "$QOL_PASS" "$QOL_RESET" "$QOL_PASS" "$QOL_RESET"
}

# ask_choice "HEADING" default_index "label|hint" [...]  ->  echoes 1-based index
# Redraws in place rather than taking the alternate screen: an installer that
# blanks the scrollback has destroyed the record of what it just did.
ask_choice() {
    local heading="$1" def="$2"; shift 2
    local n=$#
    local sel=$(( def - 1 ))
    if [[ -n "${ASSUME_YES:-}" || ! -t 0 ]]; then printf '%s' "$def"; return 0; fi
    _ask_choice_draw "$heading" "$sel" "$@" >&2
    while true; do
        _read_key
        case "$_KEY" in
            ENTER) break ;;
            QUIT)  sel=$(( def - 1 )); break ;;
            UP)    sel=$(( (sel - 1 + n) % n )) ;;
            DOWN)  sel=$(( (sel + 1) % n )) ;;
            DIGIT) if (( 10#$_KEYCH >= 1 && 10#$_KEYCH <= n )); then sel=$(( 10#$_KEYCH - 1 )); fi ;;
        esac
        printf '\033[%dA' $(( n + 3 )) >&2
        _ask_choice_draw "$heading" "$sel" "$@" >&2
    done
    printf '%s' "$(( sel + 1 ))"
}
# ‒‒ end theme block

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Back-compat: the old fstring API. New scripts should call the log_*
# helpers directly. The old "emphasis" argument is no longer supported.
# Usage: fstring "text" [type] [weight] [color]
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
fstring() {
    local text="$1" text_type="${2:-normal}" weight="${3:-normal}" color="${4:-}"
    case "$text_type" in
        title)           log_title "$text" ;;
        section|install) log_step  "$text" ;;
        warning)         log_warn  "$text" ;;
        failure)         log_err   "$text" ;;
        success)         log_ok    "$text" ;;
        *)               style_text "$text" "$weight" "$color" ;;
    esac
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Status / safety helpers
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# Report the result of the previous command.
# Usage: some_command; check_status "Description of step" $?
check_status() {
    if [ $# -ne 2 ]; then
        log_warn "check_status needs a message and an exit status. Usage: check_status <message> <exit_status>"
        return 1
    fi
    local message="$1" exit_status="$2"
    if [ "$exit_status" -eq 0 ]; then
        log_ok "$message: SUCCESS"
        return 0
    fi
    log_err "$message: FAILED (exit $exit_status)"
    return "$exit_status"
}

# Require the script to be run as root.
as_root() {
    if [ "${EUID:-$(id -u)}" -ne 0 ]; then
        log_err "Run as root.  Usage: sudo $0"
        exit 1
    fi
}

# Require the script to NOT be run as root.
not_as_root() {
    if [ "${EUID:-$(id -u)}" -eq 0 ]; then
        log_err "Do not run as root.  Usage: $0"
        exit 1
    fi
}

# Gracefully handle CTRL-C.
# NOTE: A trap is installed at the bottom of this file so this fires
# automatically in any script that sources base_functions.sh.
handle_ctrl_c() {
    echo
    log_err "Interrupted (CTRL-C). Exiting."
    exit 130
}

check_if_linux() {
    if [ "$(uname -s)" != "Linux" ]; then
        log_err "This script is intended for Linux only."
        exit 1
    fi
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# apt helpers (Debian/Ubuntu-family)
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# Refresh the package lists.
update_repo() {
    log_step "Updating package lists..."
    apt-get -o Acquire::ForceIPv4=true update
    check_status "apt-get update" $?
}

# Update package lists and upgrade all packages.
update_and_upgrade() {
    log_step "Updating and upgrading system..."
    DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::ForceIPv4=true update \
        && DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::ForceIPv4=true upgrade -y
    check_status "System update and upgrade" $?
}

# Install one or more packages.
# Usage: install_packages package1 [package2 ...]
install_packages() {
    log_step "Installing: $*"
    DEBIAN_FRONTEND=noninteractive apt-get install -y "$@"
    local rc=$?
    # Restart services that need it, when needrestart is available.
    command -v needrestart >/dev/null 2>&1 && needrestart -r a
    check_status "Installing $*" "$rc"
}

# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒
# Environment
# ‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒‒

# Install the CTRL-C trap for any script that sources this library.
trap handle_ctrl_c INT

# Import the os-release file
if [ -f /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    export OS_NAME="$NAME"
    export OS_VERSION="$VERSION"
    export OS_CODENAME="$VERSION_CODENAME"
    # Avoid leaking the rest of os-release into the calling script's env.
    unset NAME VERSION VERSION_CODENAME VERSION_ID ID ID_LIKE PRETTY_NAME \
          ANSI_COLOR LOGO CPE_NAME HOME_URL SUPPORT_URL BUG_REPORT_URL \
          PRIVACY_POLICY_URL UBUNTU_CODENAME
fi
